# Generated by Django 4.1.3 on 2022-12-29 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_course_user_is_public_module_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
