# Generated by Django 4.1.3 on 2023-01-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_assignment_assignment_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_notesFormatted',
            field=models.TextField(blank=True),
        ),
    ]
