# Generated by Django 4.1.3 on 2023-01-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_module_module_notesformatted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_notesFormatted',
            new_name='module_notesDelta',
        ),
    ]
