# Generated by Django 4.1.3 on 2023-01-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_instructor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_instructor_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_instructor_office_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
