# Generated by Django 4.1.3 on 2023-01-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_assignment_assignment_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_priority',
        ),
    ]
