# Generated by Django 4.1.3 on 2023-01-13 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_university_course_course_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='backend.university'),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_title', models.CharField(max_length=64)),
                ('discussion_desc', models.TextField(blank=True)),
                ('discussion_date', models.DateTimeField(auto_now_add=True)),
                ('discussion_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_author_discussions', to=settings.AUTH_USER_MODEL)),
                ('discussion_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_discussions', to='backend.course')),
                ('discussion_users', models.ManyToManyField(blank=True, related_name='user_discussions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('comment_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.discussion')),
            ],
        ),
    ]
