# Generated by Django 4.1.3 on 2023-01-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_course_course_university_discussion_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='discussion_course',
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussion_courses',
            field=models.ManyToManyField(blank=True, related_name='course_discussions', to='backend.course'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussion_university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='university_discussions', to='backend.university'),
            preserve_default=False,
        ),
    ]
