# Generated by Django 4.1.3 on 2023-01-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_discussion_discussion_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='discussion_courses',
            new_name='discussion_course',
        ),
    ]
