# Generated by Django 4.1.3 on 2023-01-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_discussion_courses_discussion_discussion_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='discussion_course',
            new_name='discussion_courses',
        ),
    ]
