# Generated by Django 4.1.3 on 2023-01-22 19:21

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_discussion_discussion_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_public',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.upload_path),
        ),
    ]
