# Generated by Django 4.1.3 on 2023-02-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_course_course_code_remove_course_course_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_university', 'course_code')},
        ),
    ]
